AWSTemplateFormatVersion: '2010-09-09'
Description: 'lambda-carbon

  A project lambda app to test the flexibility of lambda and SAM

  '
Globals:
  Function:
    MemorySize: 384
    Timeout: 8
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Dev stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - SharkFunction
      - Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - SharkFunction
      - Arn
Resources:
  SharkFunction:
    Properties:
      CodeUri: s3://netlab-dev/c32a00b3772d34e5819e09476b32a452
      Events:
        HelloWorld:
          Properties:
            Method: get
            Path: /hello
          Type: Api
        Stream:
          Properties:
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
            Stream:
              Fn::GetAtt:
              - StatsTable
              - StreamArn
          Type: DynamoDB
      Handler: central.kitchensink
      Role: arn:aws:iam::084075158741:role/netlab-server-executor
      Runtime: nodejs8.10
      VpcConfig:
        SecurityGroupIds:
        - sg-4b9ff335
        - sg-539cf02d
        SubnetIds:
        - subnet-c0cf7088
        - subnet-5bb24a01
        - subnet-045f9c28
        - subnet-04386838
    Type: AWS::Serverless::Function
  StatsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
