AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    lambda-carbon

    A project lambda app to test the flexibility of lambda and SAM

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 8
        MemorySize: 384


Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: central.kitchensink
            Role:    arn:aws:iam::084075158741:role/netlab-server-executor
            Runtime: nodejs8.10
            VpcConfig:
              SecurityGroupIds:
                - sg-4b9ff335
                - sg-539cf02d
              SubnetIds:
                - subnet-c0cf7088
                - subnet-5bb24a01
                - subnet-045f9c28
                - subnet-04386838
              Events:
              HelloWorld:
                Type: Api # More info about API Event Source:
                Properties:
                    Path: /hello
                    Method: get

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Dev stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/hello/"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    # HelloWorldFunctionIamRole:
    #   Description: "Implicit IAM Role created for Hello World function"
    #   Value: !GetAtt HelloWorldFunctionRole.Arn
